// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGC1k-FsdKVZjqSFke1wEdZ6kSpuv5Guc',
    appId: '1:98397686150:web:f7159e513e409bf8e74407',
    messagingSenderId: '98397686150',
    projectId: 'cleancode-poc',
    authDomain: 'cleancode-poc.firebaseapp.com',
    storageBucket: 'cleancode-poc.firebasestorage.app',
    measurementId: 'G-2FSSYRKT9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtNLapk9VwT70PpArcKqMYSLa9aXnxjjU',
    appId: '1:98397686150:android:7eccd62185ff4afbe74407',
    messagingSenderId: '98397686150',
    projectId: 'cleancode-poc',
    storageBucket: 'cleancode-poc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYfkkrkY1P66Ty1j2iGNSR2vmqXVRgRb4',
    appId: '1:98397686150:ios:017bed454ab84e8ae74407',
    messagingSenderId: '98397686150',
    projectId: 'cleancode-poc',
    storageBucket: 'cleancode-poc.firebasestorage.app',
    iosClientId: '98397686150-gn5so4lsq27g7tn8oetjbuqiq6177ohl.apps.googleusercontent.com',
    iosBundleId: 'com.example.help',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYfkkrkY1P66Ty1j2iGNSR2vmqXVRgRb4',
    appId: '1:98397686150:ios:017bed454ab84e8ae74407',
    messagingSenderId: '98397686150',
    projectId: 'cleancode-poc',
    storageBucket: 'cleancode-poc.firebasestorage.app',
    iosClientId: '98397686150-gn5so4lsq27g7tn8oetjbuqiq6177ohl.apps.googleusercontent.com',
    iosBundleId: 'com.example.help',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGC1k-FsdKVZjqSFke1wEdZ6kSpuv5Guc',
    appId: '1:98397686150:web:5ba03d8c19dadb44e74407',
    messagingSenderId: '98397686150',
    projectId: 'cleancode-poc',
    authDomain: 'cleancode-poc.firebaseapp.com',
    storageBucket: 'cleancode-poc.firebasestorage.app',
    measurementId: 'G-W8Q3G3JG5H',
  );
}
